
# tap repositories and their packages

tap homebrew/core
brew anyenv
brew awscli
brew ctags
brew fish
brew fontconfig
brew freetype
brew fzf
brew gd
brew gdbm
brew gettext
brew git
brew glib
brew graphviz
brew gts
brew h2o
brew icu4c
brew ilmbase
brew imagemagick
brew jasper
brew jpeg
brew jq
brew krb5
brew libde265
brew libffi
brew libheif
brew libomp
brew libpng
brew libtiff
brew libtool
brew libyaml
brew little-cms2
brew lua
brew mas
brew mysql
brew mysql@5.7
brew netpbm
brew nginx
brew node
brew oniguruma
brew openexr
brew openjpeg
brew openssl@1.1
brew pcre
brew pcre2
brew peco
brew perl
brew pkg-config
brew postgresql
brew postgresql@9.6
brew protobuf
brew protobuf@3.7
brew python
brew python@3.8
brew readline
brew redis
brew ruby
brew shared-mime-info
brew sqlite
brew the_silver_searcher
brew vim
brew webp
brew x265
brew xz
brew yarn
brew zlib

tap homebrew/bundle

tap homebrew/cask-drivers
cask wd-security

tap homebrew/cask-fonts
cask font-hack-nerd-font

tap homebrew/services

tap homebrew/cask
cask 1password
cask atom
cask authy
cask boostnote
cask cheatsheet
cask discord
cask docker
cask dropbox
cask figma
cask firefox
cask google-backup-and-sync
cask google-chrome
cask gyazo
cask iterm2
cask karabiner-elements
cask keyboard-cleaner
cask kindle
cask kindle-previewer
cask ngrok
cask notion
cask podcastmenu
cask postman
cask psequel
cask sequel-pro
cask slack
cask spotify
cask vagrant
cask virtualbox
cask visual-studio-code
cask xquartz
cask zoomus

tap argon/mas

tap heroku/brew
brew heroku
brew heroku-node

tap mongodb/brew
brew mongodb-community

tap rcmdnk/file
brew brew-file

tap thoughtbot/formulae
brew rcm

tap wercker/wercker
brew wercker-cli

# App Store applications
appstore 1091189122 Bear (1.7.10)
appstore 682658836 GarageBand (10.3.4)
appstore 1437226581 Horo (2.0.6)
appstore 408981434 iMovie (10.1.14)
appstore 409183694 Keynote (10.0)
appstore 409203825 Numbers (10.0)
appstore 409201541 Pages (10.0)
appstore 497799835 Xcode (11.4)
